dev_addr: 127.0.0.1:3000
edit_uri: https://github.com/natanfeitosa/portudoc/edit/main/docs/
extra:
  social:
  - icon: fontawesome/brands/x-twitter
    link: https://twitter.com/dev_natan
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/natanfeitosa
  - icon: fontawesome/brands/github
    link: https://github.com/natanfeitosa
extra_javascript:
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
hooks:
- register_portuscript_lexer.py
markdown_extensions:
- toc:
    permalink: true
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.highlight:
    anchor_linenums: true
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.superfences
- pymdownx.details
- pymdownx.arithmatex
- attr_list
- admonition
nav:
- Home: index.md
- "Vari\xE1veis e Constantes": variaveis.md
- Tipos de dados:
  - Texto: tipos/texto.md
  - Inteiro: tipos/inteiro.md
  - Decimal: tipos/decimal.md
  - Mapa: tipos/mapa.md
  - Tupla: tipos/tupla.md
  - Lista: tipos/lista.md
- Operadores: operadores.md
- Controles de Fluxo: controles.md
- "Fun\xE7\xF5es": funcoes.md
- "Fun\xE7\xF5es e constantes embutidas": embutidos.md
- Modulos:
  - "In\xEDcio": modulos/index.md
  - matematica: modulos/matematica.md
  - sistema: modulos/sistema.md
  - colorize: modulos/colorize.md
plugins:
- search:
    lang: pt
repo_name: natanfeitosa/portuscript
repo_url: https://github.com/natanfeitosa/portuscript/
site_name: Portuscript
site_url: https://portudoc.readthedocs.io/pt/latest/
theme:
  features:
  - content.code.copy
  - content.code.select
  - navigation.tabs
  - navigation.top
  - navigation.tracking
  - navigation.footer
  - search.highlight
  - search.share
  - search.suggest
  - content.action.edit
  - toc.integrate
  font:
    code: Roboto Mono
    text: Roboto
  icon:
    repo: fontawesome/brands/github
  language: pt-BR
  locale: pt_BR
  name: material
  palette:
  - accent: indigo
    media: '(prefers-color-scheme: light)'
    primary: indigo
    scheme: default
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  - accent: indigo
    media: '(prefers-color-scheme: dark)'
    primary: black
    scheme: slate
    toggle:
      icon: material/lightbulb
      name: Switch to system preference
